#!/usr/bin/node

const GYMRUN_EXPORTED_FILE_RAW = './bak/GymRun.csv';
const GYMLOG_EXPORTED_FILE_RAW = './bak/output.json';
const NEW_DEFINITION_FILE = '../GymLog/app/src/main/assets/initialData.json';

const fs = require('fs');
const {
	STATUS,
	MAPPING,
	EXCEPTIONS,
	BAR,
	BAR_SETTINGS,
	BAR_FORMULA
} = require('./constants');

const requiresBar = (() => {
	let requiresBarList = (()=>{
		let txt = fs.readFileSync(NEW_DEFINITION_FILE, 'UTF-8');
		let json = JSON.parse(txt);
		return json.filter(j=>j.bar).map(j => j.name);
	})();

	return name => {
		if (MAPPING[name]) {
			return requiresBarList.indexOf(MAPPING[name]) >= 0;
		}
		return false;
	}
})();

function parseDate(date) {
	let [d,m,y] = date.split('.');
	return `20${y}-${m}-${d}`;
}


let lastDate, lastName, lastNote;
function processWeight([date, time, name, set, weight, reps, note = ""]) {
	let bar = requiresBar(name);
	let lastBar = bar? BAR_SETTINGS[name] : undefined;

	if (bar && !lastBar) {
		throw new Error("No bar definition for: " + name);
	}

	date = parseDate(date);
	let timestamp = Date.parse(`${date} ${time}`);

	if (EXCEPTIONS[name]) {
		if (lastDate == date && lastName == name && lastNote) {
			//console.log('"'+note+'" -> "'+lastNote+'"');
		} else {
			lastDate = date;
			lastName = name;
			lastNote = note;
		}
	}

	return {
		name: MAPPING[name],
		bar: bar,
		lastBar: lastBar,
		note: note,
		timestamp: timestamp,
		weight: weight,
		reps: reps,
	}
}

function processReps(row) {

}

function processDuration(row) {

}



fs.readFile(GYMRUN_EXPORTED_FILE_RAW, 'UTF-8', (err, data) => {
	let status = STATUS.NONE;

	data.split('\r\n')
		.map(text => text.trim())
		.forEach(text => {
			if (!text || status == STATUS.DONE) 
				return;

			if (text == 'Date;Time;Exercise;Set;Weight;Reps;Note;')
				status = STATUS.WEIGHT;

			else if (text == 'Date;Time;Exercise;Set;Reps;Note;')
				status = STATUS.REPS;

			else if (text == 'Date;Time;Exercise;Duration;Note;')
				status = STATUS.DURATION;

			else if (text == 'Date;Time;Weight;Note;' || text == 'Date;Time;Waist;Note;')
				status = STATUS.DONE;
			
			else if (status == STATUS.NONE)
				return

			else if (status == STATUS.WEIGHT) {
				let res = processWeight(text.split(';'));
				console.log(res);
			} else if (status == STATUS.REPS) {
				processReps(text.split(';'));
			} else if (status == STATUS.DURATION) {
				processDuration(text.split(';'));
			}
		});
});
/**/



/*
// Check if exists translation:
fs.readFile(NEW_DEFINITION_FILE, 'UTF-8', (err,data) => {
	let names = JSON.parse(data).map(a => a.name);

	for (let es in MAPPING) {
		let en = MAPPING[es];

		if (typeof en == 'string') {
			if (names.indexOf(en) < 0) {
				console.log(es, " -- ", en)
			}
		}
	
	}
});
/**/